// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imzakckizyrynwejmwou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltemFrY2tpenlyeW53ZWptd291Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODM1MDAsImV4cCI6MjA2NzA1OTUwMH0.J6f6cvNx4ZXrSSPZCQptw3BV_NI4DlmmGlmOaqou15A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});